title = "Template Regex"

# person info, e.g., birth location, movie info, e.g., genre/language

[base_sql]
sql = '''
SELECT COUNT(*)
FROM title as t,
kind_type as kt,
movie_info as mi1,
info_type as it1,
cast_info as ci,
role_type as rt,
name as n,
info_type as it2,
person_info as pi
WHERE
t.id = ci.movie_id
AND t.id = mi1.movie_id
AND mi1.info_type_id = it1.id
AND t.kind_id = kt.id
AND ci.person_id = n.id
AND ci.role_id = rt.id
AND n.id = pi.person_id
AND pi.info_type_id = it2.id
AND (Xit1)
AND (Xit2)
AND (Xmovie_info)
AND (Xperson_info)
AND (Xmovie_kind)
AND (Xrole)
AND (Xgender)
AND (Xprod_year_up)
AND (Xprod_year_low)
'''

# template 1
[[templates]]

  name = "1a"

  # all the unknown predicates in the base sql will be specified in groups
  [[templates.predicates]]
  type = "list"
  columns = ["t.production_year"]
  keys = ["Xprod_year_low", "Xprod_year_up"]
  dependencies = 0
  options = [[1925, 1975], [1975, 2015], [1875, 1975], [1925,
  2015], [1950, 1990], [1990, 2015]]
  sampling_method = "uniform"
  pred_type = "range"
  min_samples = 1
  max_samples = 1

  [[templates.predicates]]
  type = "sql"
  columns = ["kt.kind"]
  keys = ["Xmovie_kind"]
  dependencies = 1
  pred_type = "IN"

  # we want to sample this based on the ALREADY selected value for company name /
  # company type
  sql = '''
  SELECT kt.kind, count(*)
  FROM title as t, kind_type as kt
  WHERE t.kind_id = kt.id
  AND (Xprod_year_up)
  AND (Xprod_year_low)
  GROUP BY kt.kind
  ORDER BY count(*) desc
  '''

  sampling_method = "quantile"
  num_quantiles = 2
  min_samples = 3
  max_samples = 15

  [[templates.predicates]]

  type = "sql"
  columns = ["n.gender", "rt.role"]
  keys = ["Xgender", "Xrole"]
  dependencies = 0
  pred_type = "IN"

  sql = '''
  SELECT n.gender, rt.role, count(*)
  FROM cast_info as ci,
  name as n, role_type as rt
  WHERE ci.person_id = n.id
  AND ci.role_id = rt.id
  GROUP BY n.gender, rt.role
  ORDER BY count(*) desc
  '''

  sampling_method = "quantile"
  num_quantiles = 2
  min_samples = 1
  max_samples = 4

  [[templates.predicates]]
  type = "sql"
  columns = ["it1.id"]
  keys = ["Xit1"]
  dependencies = 1
  pred_type = "IN"

  sampling_method = "quantile"
  num_quantiles = 1
  min_samples = 1
  max_samples = 1

  sql = '''
  SELECT it.id, count(*)
	FROM movie_info as mi, info_type as it, title as t,
  kind_type as kt
	WHERE t.id = mi.movie_id
	AND mi.info_type_id = it.id
  AND kt.id = t.kind_id
  AND (Xprod_year_up)
  AND (Xprod_year_low)
  AND (Xmovie_kind)
	GROUP BY it.id HAVING COUNT(*) > 50000
  ORDER BY COUNT(*) DESC
  '''

  [[templates.predicates]]
  type = "sql"
  columns = ["mi1.info"]
  keys = ["Xmovie_info"]
  dependencies = 1
  pred_type = "ILIKE"

  sampling_method = "quantile"
  num_quantiles = 2
  min_samples = 1
  max_samples = 4

  sql = '''
  SELECT mi.info
	FROM movie_info as mi, info_type as it1, title as t,
  kind_type as kt
	WHERE t.id = mi.movie_id
	AND mi.info_type_id = it1.id
  AND kt.id = t.kind_id
  AND (Xprod_year_up)
  AND (Xprod_year_low)
  AND (Xmovie_kind)
  AND (Xit1)
  '''
