# trying to be as complicated as possible without including title et. al tables

title = "Template 5"

# potentially we don't need all those join cycles
[base_sql]
sql = '''SELECT COUNT(*)
FROM
aka_name as an,
name as n,
cast_info as ci,
person_info as pi1,
info_type as it1,
role_type as rt,
char_name as chn
WHERE
n.id = ci.person_id
AND ci.person_id = pi1.person_id
AND it1.id = pi1.info_type_id
AND n.id = pi1.person_id
AND n.id = an.person_id
AND ci.person_id = an.person_id
AND an.person_id = pi1.person_id
AND rt.id = ci.role_id
AND chn.id = ci.person_role_id
AND n.gender IN (Xgender)
AND n.name IN (Xname)
AND ci.note IN (Xcast_note)
AND rt.role IN (Xrole)
AND it1.id IN (Xit1)
AND pi1.info IN (Xpi1)
'''
# template 1
[[templates]]

  name = "5a"

  # all the unknown predicates in the base sql will be specified in groups
  [[templates.predicates]]
  type = "list"
  columns = ["it1.id"]
  keys = ["Xit1"]
  dependencies = 0
  #options = ["25", "26", "31", "32", "34", "37"]
  options = ["34"]
  #options = ["19", "25", "26", "31", "32", "34", "37"]
  sampling_method = "uniform"
  pred_type = "in"
  min_samples = 1
  max_samples = 1

  [[templates.predicates]]

  type = "sql"
  columns = ["n.gender"]
  keys = ["Xgender"]
  dependencies = 0
  sampling_method = "uniform"
  sql = '''SELECT DISTINCT n.gender FROM name as n WHERE n.gender IS NOT NULL'''
  pred_type = "in"
  min_samples = 1
  max_samples = 2

  [[templates.predicates]]
  type = "sql"
  columns = ["pi1.info", "n.name"]
  keys = ["Xpi1", "Xname"]
  dependencies = 1

  # we want to sample this based on the ALREADY selected value for company name /
  # company type
  sql = '''
  SELECT pi1.info, n.name, count(*)
  FROM person_info as pi1,
  info_type as it1,
  cast_info as ci,
  name as n
  WHERE pi1.info_type_id = it1.id
  AND pi1.person_id = ci.person_id
  AND it1.id = Xit1
  AND n.id = pi1.person_id
  AND n.gender IN (Xgender)
  GROUP BY pi1.info, n.name
  HAVING count(*) > 500
  ORDER BY count(*) desc
  '''

  sampling_method = "quantile"
  num_quantiles = 2
  min_samples = 5
  max_samples = 15

  #--> highly correlated columns.
  [[templates.predicates]]
  type = "sql"
  columns = ["ci.note", "rt.role"]
  keys = ["Xcast_note", "Xrole"]
  dependencies = 0
  sampling_method = "quantile"
  num_quantiles = 2

  sql = '''
  SELECT ci.note, rt.role, COUNT(*) FROM role_type as rt, cast_info as ci
  WHERE rt.id = ci.role_id
  AND rt.role IS NOT NULL
  AND ci.note IS NOT NULL
  GROUP BY
  ci.note, rt.role HAVING COUNT(*) > 600
  ORDER BY
  COUNT(*) DESC;
  '''

  min_samples = 3
  max_samples = 15
