title = "Test"

[base_sql]
sql = '''SELECT COUNT(*)
FROM
tag as t,
site as s,
question as q,
tag_question as tq
WHERE
t.site_id = s.site_id
AND q.site_id = s.site_id
AND tq.site_id = s.site_id
AND tq.question_id = q.id
AND tq.tag_id = t.id
AND (Xsite_name)
AND (Xtag_name)
AND (Xquestion_view_low)
AND (Xquestion_view_up)
'''

# template 1
[[templates]]

  name = "test"

  [[templates.predicates]]
  type = "list"
  columns = ["q.view_count"]
  keys = ["Xquestion_view_low", "Xquestion_view_up"]
  dependencies = 0
  options = [[0,100], [0,1000], [0,1000000], [100,1000], [100,1000000], [1000,100000]]
  sampling_method = "uniform"
  pred_type = "range"
  min_samples = 1
  max_samples = 1

  # all the unknown predicates in the base sql will be specified in groups
  [[templates.predicates]]
  type = "sqls"
  columns = ["s.site_name"]
  keys = ["Xsite_name"]
  dependencies = 0

  pred_type = "in"

  sqls = ["SELECT s.site_name FROM site as s, question as q WHERE s.site_name IN ('stackoverflow') AND q.site_id = s.site_id LIMIT 10",
  "SELECT s.site_name, count(*) FROM site as s, question as q WHERE q.site_id = s.site_id GROUP BY s.site_name HAVING COUNT(*) > 15000 ORDER BY count(*) desc"]

  sampling_method = "quantile"
  num_quantiles = 2
  min_samples = 1
  max_samples = 1

  # all the unknown predicates in the base sql will be specified in groups
  [[templates.predicates]]

  # Length of these lists should be the same
  type = "sql"
  columns = ["t.name"]
  keys = ["Xtag_name"]
  dependencies = 1
  pred_type = "in"

  sql = '''
  SELECT t.name, count(*)
  FROM
  tag as t,
  site as s,
  question as q,
  tag_question as tq
  WHERE
  t.site_id = s.site_id
  AND q.site_id = s.site_id
  AND tq.site_id = s.site_id
  AND tq.question_id = q.id
  AND tq.tag_id = t.id
  AND (Xsite_name)
  AND (Xquestion_view_low)
  AND (Xquestion_view_up)
  GROUP BY t.name
  HAVING COUNT(*) > 500
  ORDER BY count(*) desc
  '''

  sampling_method = "quantile"
  num_quantiles = 2
  min_samples = 2
  max_samples = 15
